FROM registry.cn-beijing.aliyuncs.com/chenmin/standalone-chrome-debug-novnc:gt
LABEL maintainer=admin@chenmin.org

COPY init /home/seluser/.fluxbox/init
COPY gt_black.png /usr/share/images/fluxbox/ubuntu-light.png

 
