FROM registry.cn-beijing.aliyuncs.com/chenmin/standalone-chrome-debug-novnc:gt
LABEL maintainer=admin@chenmin.org

COPY init /home/seluser/.fluxbox/init
COPY apps /home/seluser/.fluxbox/apps
COPY keys /home/seluser/.fluxbox/keys
COPY lastwallpaper /home/seluser/.fluxbox/lastwallpaper
COPY menu /home/seluser/.fluxbox/menu
COPY overlay /home/seluser/.fluxbox/overlay
COPY windowmenu /home/seluser/.fluxbox/windowmenu
COPY gt_black.png /usr/share/images/fluxbox/ubuntu-light.png

 
